### ISSUE TITLE
[QMail] Decrypt msg fails due to unknown recipient when using aliases

### ISSUE THREAD

**Issue by Mark-BC** [Qortal/Q-Apps#4]
In Qortal UI 4.0.4 I sent an email to a recipient using an Alias.  Then I tried to reread my sent email and received an unknown-recipient error.

I suggest that all emails I send should be encrypted for the sender's public key and each recipient's public key separately, so it should be irrelevant who the recipient is when the sender goes to decrypt the message.

My understanding is that usually text (emails, docs, whatever) is encrypted with a symmetric key (for speed) then the symmetric key is encrypted with each recipient's (and the sender's) public key, so they can all decrypt the message independently.  When going to decrypt, for privacy, the symmetric key encryptions are not labelled so the receiver won't know which of the symmetric key encryptions is for their public key, so they will have to try all of them until one decrypts properly.  But one of them will also be the sender's so the sender will be able to decrypt as well.

I suggest about Aliases, they should just be a clear-text list of labels that will match that message during a search, with no hint as to which symmetric-key encryption any alias belongs to.  So it should be possible to assign a list of Aliases (hopefully matching the selected list of recipients) for a message.  If an alias is included without the corresponding true userid, then that public key will be missing and if an alias is missed, then the message will be encrypted for someone who will never be able to pick it up.

I do not know how encryption or aliases were implemented in QORTAL but I would definitely like to understand it better.

Here is the image of the bug just after clicking on the first of the three emails I just sent.
![Screenshot 2023-05-10 at 19 48 44](https://github.com/Qortal/Q-Apps/assets/26406807/16af97e1-32f8-44ec-bdcd-7938637e7dc0)

**Comment by QuickMythril** [comment]
Thank you.  The suggestion above was implented when group encryption was added.  This should be resolved.
